//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcleChange
{
    using System;
    using System.Collections.Generic;
    
    public partial class card_make
    {
        public int card_no { get; set; }
        public int cust_no { get; set; }
        public Nullable<decimal> foregift { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<System.DateTime> validdt { get; set; }
        public Nullable<int> status { get; set; }
        public string @operator { get; set; }
        public Nullable<System.DateTime> createdt { get; set; }
        public Nullable<System.DateTime> parkStartDT { get; set; }
    }
}
