//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcleChange
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int cust_no { get; set; }
        public string cust_name { get; set; }
        public string cust_password { get; set; }
        public string cust_nick { get; set; }
        public Nullable<int> sex { get; set; }
        public string phone_no { get; set; }
        public string mobile { get; set; }
        public string idcard { get; set; }
        public string address { get; set; }
        public string remark { get; set; }
        public string @operator { get; set; }
        public Nullable<System.DateTime> createdt { get; set; }
        public Nullable<int> wrkNo { get; set; }
        public Nullable<int> deptNo { get; set; }
        public string photo { get; set; }
        public Nullable<int> cust_level { get; set; }
    }
}
