//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcleChange
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Record
    {
        public int ID { get; set; }
        public string CardNo { get; set; }
        public string Cust_nick { get; set; }
        public string Cust_name { get; set; }
        public string State { get; set; }
        public string SN { get; set; }
        public string ControlNo { get; set; }
        public string ReadNo { get; set; }
        public string DoorName { get; set; }
        public System.DateTime KaiTime { get; set; }
    }
}
